name: Fetch Vault Secrets
on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string
    outputs:
      dev_path:
        description: "Development Path"
        value: ${{ steps.fetch-secrets.outputs.dev_path }}
      live_path:
        description: "Live Path"
        value: ${{ steps.fetch-secrets.outputs.live_path }}
      ms_teams_webhook_uri:
        description: "MS Teams Webhook URI"
        value: ${{ steps.fetch-secrets.outputs.ms_teams_webhook_uri }}
      remote_host:
        description: "Remote Host"
        value: ${{ steps.fetch-secrets.outputs.remote_host }}
      remote_pwd:
        description: "Remote Password"
        value: ${{ steps.fetch-secrets.outputs.remote_pwd }}
      remote_user:
        description: "Remote User"
        value: ${{ steps.fetch-secrets.outputs.remote_user }}

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets using Docker action
        id: fetch-secrets
        uses: docker://ghcr.io/nimbits/vault-action:latest
        with:
          vault_url: ${{ inputs.vault_url }}
          secret_path: ${{ inputs.secret_path }}
