name: Fetch Vault Secrets
on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ inputs.vault_url }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          secrets: |
            secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
            secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;
    outputs:
      dev_path: ${{ env.AWS_ACCESS_KEY_ID }}
      live_path: ${{ env.AWS_ACCESS_KEY_ID }}
      ms_teams_webhook_uri: ${{ env.AWS_ACCESS_KEY_ID }}
      remote_host: ${{ env.AWS_ACCESS_KEY_ID }}
      remote_pwd: ${{ env.AWS_ACCESS_KEY_ID }}
      remote_user: ${{ env.AWS_ACCESS_KEY_ID }}
