name: Fetch Vault Secrets
on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string
    #outputs:
      ####


jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set hardcoded outputs
        id: fetch-secrets
        run: |
          echo "::set-output name=dev_path::hardcoded_dev_path"
          echo "::set-output name=live_path::hardcoded_live_path"
          echo "::set-output name=ms_teams_webhook_uri::hardcoded_webhook_uri"
          echo "::set-output name=remote_host::hardcoded_remote_host"
          echo "::set-output name=remote_pwd::hardcoded_remote_pwd"
          echo "::set-output name=remote_user::hardcoded_remote_user"
    outputs:
      dev_path: ${{ steps.fetch-secrets.outputs.dev_path }}
      live_path: ${{ steps.fetch-secrets.outputs.live_path }}
      ms_teams_webhook_uri: ${{ steps.fetch-secrets.outputs.ms_teams_webhook_uri }}
      remote_host: ${{ steps.fetch-secrets.outputs.remote_host }}
      remote_pwd: ${{ steps.fetch-secrets.outputs.remote_pwd }}
      remote_user: ${{ steps.fetch-secrets.outputs.remote_user }}
