name: Fetch Vault Secrets
on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ inputs.vault_url }}
          method: github
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            ${{ inputs.secret_path }} dev_path
            ${{ inputs.secret_path }} live_path
            ${{ inputs.secret_path }} ms_teams_webhook_uri
            ${{ inputs.secret_path }} remote_host
            ${{ inputs.secret_path }} remote_pwd
            ${{ inputs.secret_path }} remote_user
    outputs:
      dev_path: ${{ steps.fetch-secrets.outputs.dev_path }}
      live_path: ${{ steps.fetch-secrets.outputs.live_path }}
      ms_teams_webhook_uri: ${{ steps.fetch-secrets.outputs.ms_teams_webhook_uri }}
      remote_host: ${{ steps.fetch-secrets.outputs.remote_host }}
      remote_pwd: ${{ steps.fetch-secrets.outputs.remote_pwd }}
      remote_user: ${{ steps.fetch-secrets.outputs.remote_user }}
