name: Fetch SW Vault Secrets
on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ inputs.vault_url }}
          method: token
          token: ${{ secrets.vault_token }}
          secrets: |
            ${{ inputs.secret_path }} remote_host | REMOTE_HOST ;
            ${{ inputs.secret_path }} remote_user | REMOTE_USER ;
            ${{ inputs.secret_path }} remote_pwd | REMOTE_PWD ;
            ${{ inputs.secret_path }} ms_teams_webhook_uri | MS_TEAMS_WEBHOOK_URI ;
            ${{ inputs.secret_path }} live_path | LIVE_PATH ;
            ${{ inputs.secret_path }} dev_path | DEV_PATH ;
    outputs:
      dev_path: test
      live_path: test
      ms_teams_webhook_uri: test
      remote_host: test
      remote_pwd: test
      remote_user: test

