name: Fetch SW Vault Secrets
on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    outputs:
      dev_path: ${{ steps.set-outputs.outputs.dev_path }}
      live_path: ${{ steps.set-outputs.outputs.live_path }}
      ms_teams_webhook_uri: ${{ steps.set-outputs.outputs.ms_teams_webhook_uri }}
      remote_host: ${{ steps.set-outputs.outputs.remote_host }}
      remote_pwd: ${{ steps.set-outputs.outputs.remote_pwd }}
      remote_user: ${{ steps.set-outputs.outputs.remote_user }}
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ inputs.vault_url }}
          method: token
          token: ${{ secrets.vault_token }}
          secrets: |
            ${{ inputs.secret_path }} remote_host | REMOTE_HOST ;
            ${{ inputs.secret_path }} remote_user | REMOTE_USER ;
            ${{ inputs.secret_path }} remote_pwd | REMOTE_PWD ;
            ${{ inputs.secret_path }} ms_teams_webhook_uri | MS_TEAMS_WEBHOOK_URI ;
            ${{ inputs.secret_path }} live_path | LIVE_PATH ;
            ${{ inputs.secret_path }} dev_path | DEV_PATH ;

      - name: Set outputs
        id: set-outputs
        run: |
          echo "dev_path=test" >> $GITHUB_ENV
          echo "live_path=test" >> $GITHUB_ENV
          echo "ms_teams_webhook_uri=test" >> $GITHUB_ENV
          echo "remote_host=test" >> $GITHUB_ENV
          echo "remote_pwd=test" >> $GITHUB_ENV
          echo "remote_user=test" >> $GITHUB_ENV
