name: Deploy to Shopware 5

on:
  workflow_call:
    inputs:
      is_prod:
        required: false
        type: boolean
        default: false
      check_tag:
        required: false
        type: boolean
        default: true
      repo_name:
        required: false
        type: 'string'
        default: ${{ github.event.repository.name }}
      is_theme:
        required: true
        type: boolean
    secrets:
      CURR_VAULT_PATH:
        required: true
      CURR_VAULT_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: latest_tag
      uses: actions-ecosystem/action-get-latest-tag@v1.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate tag format
      if: inputs.check_tag
      run: |
        if ! [[ "${{ steps.latest_tag.outputs.tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag does not match the format '[0-9]+.[0-9]+.[0-9]+'! Consider removing the tag."
          exit 1
        fi

    - name: Remove unnecessary files
      run: |
        rm -rf README.md .git* .eslint* .env* .prettier* .husky commitlint.config.js || true

    - name: Prepare and Zip
      run: |
        mkdir -p "${{ inputs.repo_name }}"

        shopt -s dotglob
        mv $(ls -A | grep -v -E "^(${{ inputs.repo_name }}|\.git|\.github|tests|phpunit\.xml|phpstan\.neon|\.php-cs-fixer\.php)$") "${{ inputs.repo_name }}/"

        find . -mindepth 1 ! -regex "^./${{ inputs.repo_name }}\(/.*\)?$" -delete
        zip -r "/tmp/${{ inputs.repo_name }}-${{ github.ref_name }}.zip" "${{ inputs.repo_name }}"


    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.7.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/${{ inputs.repo_name }}-${{ github.ref_name }}.zip
        asset_name: ${{ inputs.repo_name }}.zip
        tag: ${{ github.ref_name }}
        overwrite: false