name: Deploy to Shopware 5

on:
  workflow_call:
    inputs:
      remote_host:
        required: true
        type: string
      remote_user:
        required: true
        type: string
      target_path:
        required: true
        type: string
      is_theme:
        required: true
        type: boolean
      deployFolderName:
        required: false
        type: string
    secrets:
      REMOTE_PWD:
        required: true
      MS_TEAMS_WEBHOOK_URI:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Remove unnecessary files
      run: |
        rm -rf README.md .git* .eslint* .env* .prettier*

    - name: Deployment to temporary directory
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.remote_host }}
        username: ${{ inputs.remote_user }}
        password: ${{ secrets.REMOTE_PWD }}
        target: ${{ inputs.target_path }}/ci_temp/${{ inputs.deployFolderName || github.event.repository.name }}
        source: ./*
        strip_components: 0

    - name: Replace old directory with new one
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.remote_host }}
        username: ${{ inputs.remote_user }}
        password: ${{ secrets.REMOTE_PWD }}
        script: |
          folder_name=${{ inputs.deployFolderName || github.event.repository.name }}
          if [ ${{ inputs.is_theme }} == true ]; then
            deployment_path="${{ inputs.target_path }}/themes/Frontend/$folder_name"
          else
            deployment_path="${{ inputs.target_path }}/custom/plugins/$folder_name"
          fi
          rm -rf $deployment_path
          mv ${{ inputs.target_path }}/ci_temp/$folder_name $deployment_path
    
    - name: Clear Cache & Theme compile & Assets install
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.remote_host }}
        username: ${{ inputs.remote_user }}
        password: ${{ secrets.REMOTE_PWD }}
        script: |
          cd ${{ inputs.target_path }}
          bin/console sw:cache:clear
          bin/console sw:theme:cache:generate

    - name: Notify teams on success
      if: success()
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: 'Deployment successful!'
        notification-color: '3FBA50' # Green
        timezone: Europe/Berlin


    - name: Notify teams on failure
      if: failure()
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: 'Deployment failed!'
        notification-color: 'F85149'  # Red 
        timezone: Europe/Berlin
