name: Deploy to Shopware 6

on:
  workflow_call:
    inputs:
      remote_host:
        required: true
        type: string
      remote_user:
        required: true
        type: string
      remote_pwd:
        required: true
        type: string
      target_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get latest tag
      id: latest_tag
      uses: actions-ecosystem/action-get-latest-tag@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Update version in composer.json
      run: jq '.version = "${{ steps.latest_tag.outputs.tag }}"' composer.json > composer.tmp.json && mv composer.tmp.json composer.json

    - name: Create list of files to exclude
      run: echo "README.md .git* .eslint* .env* .prettier*" > files_to_exclude.txt
    
    - name: Create list of files to include
      run: ls -A1 | grep -v -F -f files_to_exclude.txt > files_to_include.txt

    - name: Deployment to temporary directory
      uses: appleboy/scp-action@master
      with:
          HOST: ${{ secrets.REMOTE_HOST }}
          PORT: 22
          USERNAME: ${{ secrets.REMOTE_USER }}
          PASSWORD: ${{ secrets.REMOTE_PWD }}
          target: ${{ inputs.target_path }}/ci_temp/${{ github.event.repository.name }}
          source: ./files_to_include.txt
          strip_components: 0

    - name: Replace old directory with new one
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.remote_host }}
        username: ${{ inputs.remote_user }}
        password: ${{ inputs.remote_pwd }}
        script: |
          rm -rf ${{ inputs.target_path }}/custom/plugins/${{ github.event.repository.name }}
          mv ${{ inputs.target_path }}/ci_temp/${{ github.event.repository.name }} ${{ inputs.target_path }}/custom/plugins/${{ github.event.repository.name }}
