name: Return Test - Reusable workflow

on:
  workflow_call:
    inputs:
      vault_url:
        required: false
        type: string
      secret_path:
        required: false
        type: string
    secrets:
      vault_token:
        required: false
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.fetch_secrets.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.fetch_secrets.outputs.output2 }}

jobs:
  fetch_secrets:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
