name: Return Test - Reusable workflow

on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
    outputs:
      remote_host:
        value: ${{ jobs.fetch_secrets.outputs.remote_host }}
      remote_user:
        value: ${{ jobs.fetch_secrets.outputs.remote_user }}
      remote_pwd:
        value: ${{ jobs.fetch_secrets.outputs.remote_pwd }}
      ms_teams_webhook_uri:
        value: ${{ jobs.fetch_secrets.outputs.ms_teams_webhook_uri }}
      live_path:
        value: ${{ jobs.fetch_secrets.outputs.live_path }}
      dev_path:
        value: ${{ jobs.fetch_secrets.outputs.dev_path }}

jobs:
  fetch_secrets:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      remote_host: ${{ steps.fetch-secrets.outputs.REMOTE_HOST }}
      remote_user: ${{ steps.fetch-secrets.outputs.REMOTE_USER }}
      remote_pwd: ${{ steps.fetch-secrets.outputs.REMOTE_PWD }}
      ms_teams_webhook_uri: ${{ steps.fetch-secrets.outputs.MS_TEAMS_WEBHOOK_URI }}
      live_path: ${{ steps.fetch-secrets.outputs.LIVE_PATH }}
      dev_path: ${{ steps.fetch-secrets.outputs.DEV_PATH }}
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: ${{ inputs.vault_url }}
          method: token
          token: ${{ secrets.vault_token }}
          secrets: |
            ${{ inputs.secret_path }} remote_host | REMOTE_HOST ;
            ${{ inputs.secret_path }} remote_user | REMOTE_USER ;
            ${{ inputs.secret_path }} remote_pwd | REMOTE_PWD ;
            ${{ inputs.secret_path }} ms_teams_webhook_uri | MS_TEAMS_WEBHOOK_URI ;
            ${{ inputs.secret_path }} live_path | LIVE_PATH ;
            ${{ inputs.secret_path }} dev_path | DEV_PATH ;
