name: Return Test - Reusable workflow

on:
  workflow_call:
    inputs:
      vault_url:
        required: true
        type: string
      secret_path:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
    outputs:
      remote_host:
        value: ${{ jobs.fetch_secrets.outputs.remote_host }}
      remote_user:
        value: ${{ jobs.fetch_secrets.outputs.remote_user }}
      remote_pwd:
        value: ${{ jobs.fetch_secrets.outputs.remote_pwd }}
      ms_teams_webhook_uri:
        value: ${{ jobs.fetch_secrets.outputs.ms_teams_webhook_uri }}
      live_path:
        value: ${{ jobs.fetch_secrets.outputs.live_path }}
      dev_path:
        value: ${{ jobs.fetch_secrets.outputs.dev_path }}

jobs:
  fetch_secrets:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      remote_host: ${{ steps.set_outputs.outputs.remote_host }}
      remote_user: ${{ steps.set_outputs.outputs.remote_user }}
      remote_pwd: ${{ steps.set_outputs.outputs.remote_pwd }}
      ms_teams_webhook_uri: ${{ steps.set_outputs.outputs.ms_teams_webhook_uri }}
      live_path: ${{ steps.set_outputs.outputs.live_path }}
      dev_path: ${{ steps.set_outputs.outputs.dev_path }}
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: ${{ inputs.vault_url }}
          method: token
          token: ${{ secrets.vault_token }}
          secrets: |
            ${{ inputs.secret_path }} remote_host | REMOTE_HOST ;
            ${{ inputs.secret_path }} remote_user | REMOTE_USER ;
            ${{ inputs.secret_path }} remote_pwd | REMOTE_PWD ;
            ${{ inputs.secret_path }} ms_teams_webhook_uri | MS_TEAMS_WEBHOOK_URI ;
            ${{ inputs.secret_path }} live_path | LIVE_PATH ;
            ${{ inputs.secret_path }} dev_path | DEV_PATH ;

      - id: set_outputs
        run: echo "remote_host=bob.nimbits-hosting.de" >> $GITHUB_OUTPUT
             echo "remote_user=${{ env.REMOTE_USER }}" >> $GITHUB_OUTPUT
             echo "remote_pwd=${{ env.REMOTE_PWD }}" >> $GITHUB_OUTPUT
             echo "ms_teams_webhook_uri=${{ env.MS_TEAMS_WEBHOOK_URI }}" >> $GITHUB_OUTPUT
             echo "live_path=${{ env.LIVE_PATH }}" >> $GITHUB_OUTPUT
             echo "dev_path=${{ env.DEV_PATH }}" >> $GITHUB_OUTPUT
