name: Return Test - Reusable workflow

on:
  workflow_call:
    inputs:
      vault_url:
        required: false
        type: string
      secret_path:
        required: false
        type: string
    secrets:
      vault_token:
        required: false
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.fetch_secrets.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.fetch_secrets.outputs.output2 }}

jobs:
  fetch_secrets:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - name: Fetch secrets from Vault
        id: fetch-secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: ${{ inputs.vault_url }}
          method: token
          token: ${{ secrets.vault_token }}
          secrets: |
            ${{ inputs.secret_path }} remote_host | REMOTE_HOST ;
            ${{ inputs.secret_path }} remote_user | REMOTE_USER ;
            ${{ inputs.secret_path }} remote_pwd | REMOTE_PWD ;
            ${{ inputs.secret_path }} ms_teams_webhook_uri | MS_TEAMS_WEBHOOK_URI ;
            ${{ inputs.secret_path }} live_path | LIVE_PATH ;
            ${{ inputs.secret_path }} dev_path | DEV_PATH ;

      - name: Debug - Echo Fetched Secrets
        run: |
          echo "Debug - Remote Host: ${{ env.REMOTE_HOST }}"
          echo "Debug - Remote Host: ${{ env.REMOTE_USER }}"
          echo "Debug - Remote Host: ${{ env.MS_TEAMS_WEBHOOK_URI }}"
          echo "Debug - Remote Host: ${{ env.LIVE_PATH }}"
          echo "Debug - Remote Host: ${{ env.DEV_PATH }}"

      - name: Step following 'Import Secrets'
        run: |
          touch secrets.json
          echo '${{ toJson(steps.fetch-secrets.outputs) }}' >> secrets.json

      - name: Output secrets.json content
        run: cat secrets.json

      - id: step1
        run: echo "firstword=${{ env.REMOTE_HOST }}" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=${{ steps.fetch-secrets.outputs.REMOTE_HOST }}" >> $GITHUB_OUTPUT
